LinkHideExtensions: false
SiteTitle: Musings
LinkRoot: "=> Config.FromSetting<string>(\"LINK_ROOT\")"
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = Context.GetString("Title");
    return  string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle}: {title}";
  }
Copyright: => $"Copyright © {DateTime.Now.Year} by me"

